/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import AppPackage.AnimationClass;
import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import com.microsoft.sqlserver.jdbc.SQLServerException;
//import com.sun.awt.AWTUtilities;
import Conexiones.prueba;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author palmachris7
 */
public class Login extends javax.swing.JFrame {
    int x,y;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       // AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icons8_user_96px.png")).getImage());
    }
    
    void loguearse() throws SQLException{
        SQLServerDataSource ds = new SQLServerDataSource();
        
        ds.setServerName("localhost");
        ds.setDatabaseName("Tienda");
        ds.setUser("sa");
        ds.setPassword("123");
        ds.setPortNumber(1433);
        
        try {
            Connection cn =ds.getConnection();
            PreparedStatement ps = cn.prepareStatement("select * from Usuario where nombre=? and contraseña=?");
            ResultSet rs =ps.executeQuery();
        } catch (SQLServerException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImgLog = new javax.swing.JLabel();
        lblIngresoContra = new javax.swing.JLabel();
        lblIngresoUsuario = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        passContraseña = new javax.swing.JPasswordField();
        lblCerrarL = new javax.swing.JLabel();
        lblMinimizarL = new javax.swing.JLabel();
        lblMenul = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblDataBase = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(346, 437));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(60, 74, 150)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_96px.png"))); // NOI18N
        jPanel1.add(lblImgLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        lblIngresoContra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIngresoContra.setForeground(new java.awt.Color(60, 74, 150));
        lblIngresoContra.setText("Ingrese Contraseña:");
        jPanel1.add(lblIngresoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 150, -1));

        lblIngresoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIngresoUsuario.setForeground(new java.awt.Color(60, 74, 150));
        lblIngresoUsuario.setText("Ingrese Usuario:");
        jPanel1.add(lblIngresoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, -1));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(60, 74, 150));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(null);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_filled_12px.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_key_12px_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(60, 74, 150)));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, 20));

        passContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(60, 74, 150)));
        passContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passContraseñaKeyPressed(evt);
            }
        });
        jPanel1.add(passContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 250, -1));

        lblCerrarL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_multiply_20px.png"))); // NOI18N
        lblCerrarL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarLMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        lblMinimizarL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_20px.png"))); // NOI18N
        lblMinimizarL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizarL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarLMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimizarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        lblMenul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_menu_2_filled_18px_1.png"))); // NOI18N
        lblMenul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMenul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenulMouseClicked(evt);
            }
        });
        jPanel1.add(lblMenul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        lblAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_info_filled_18px.png"))); // NOI18N
        lblAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutMouseClicked(evt);
            }
        });
        jPanel1.add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -50, -1, -1));

        lblDataBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_database_18px.png"))); // NOI18N
        lblDataBase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDataBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDataBaseMouseClicked(evt);
            }
        });
        jPanel1.add(lblDataBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 346, 437));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
      
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void lblMinimizarLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarLMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarLMouseClicked

    private void lblCerrarLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarLMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCerrarLMouseClicked

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
    String usuario = txtUsuario.getText();
	String contraseña= passContraseña.getText();
        if ( usuario.equals("user") && contraseña.equals("user")) {
					PrincipalUser PrincipalAdmin = new PrincipalUser();
					 this.dispose();
					 PrincipalAdmin.setVisible(true);
					 
			}
			
        else if (usuario.equals("admin") && contraseña.equals("admin")){
					PrincipalAdmin Principal = new PrincipalAdmin();
					 this.dispose();
					 Principal.setVisible(true);
	 }
        else{
                    txtUsuario.setText(null);
					passContraseña.setText(null);
					JOptionPane.showMessageDialog(null, " Usuario o Contraseña incorrectos");
        
        
        }			 
        
      
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void passContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passContraseñaKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){ 
          String usuario = txtUsuario.getText();
	String contraseña= passContraseña.getText();
        if ( usuario.equals("admin") && contraseña.equals("admin")) {
					PrincipalAdmin Principal = new PrincipalAdmin();
					 this.dispose();
					 Principal.setVisible(true);
					 
			}
			
	else{
					txtUsuario.setText(null);
					passContraseña.setText(null);
					JOptionPane.showMessageDialog(null, " Usuario o Contraseña incorrectos");
	 }
			
       }
    }//GEN-LAST:event_passContraseñaKeyPressed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void lblMenulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenulMouseClicked
        AnimationClass animacion= new AnimationClass();
        animacion.jLabelYDown(-50, 40, 10, 5, lblAbout);
        
        //regresa
        animacion.jLabelYUp(40, -50, 10, 5, lblAbout);
        
         animacion.jLabelYDown(-50, 60, 10, 5, lblDataBase);
        
        //regresa
        animacion.jLabelYUp(60, -50, 10, 5, lblDataBase);
        
    }//GEN-LAST:event_lblMenulMouseClicked

    private void lblDataBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDataBaseMouseClicked
        prueba prueba = new prueba();
        this.dispose();
	prueba.setVisible(true);
    }//GEN-LAST:event_lblDataBaseMouseClicked

    private void lblAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseClicked
        try { 
         String url = "https://pe.linkedin.com/in/palmachris7";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_lblAboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblCerrarL;
    private javax.swing.JLabel lblDataBase;
    private javax.swing.JLabel lblImgLog;
    private javax.swing.JLabel lblIngresoContra;
    private javax.swing.JLabel lblIngresoUsuario;
    private javax.swing.JLabel lblMenul;
    private javax.swing.JLabel lblMinimizarL;
    private javax.swing.JPasswordField passContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
